services:
  critrdevex.api:
    image: ${DOCKER_REGISTRY-}critrdevexapi
    container_name: api
    build:
      context: .
      dockerfile: CritRDevEx.API/Dockerfile

  critrdevex.database:
    image: postgres:latest
    container_name: database
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/database:/var/lib/postgresql/data
    ports:
      - 5432:5432
